export const ctaCopy = {
  heroCta: 'Create My Coupons',
  sendWithLove: 'Send with Love',
  saveMyCoupons: 'Save My Coupons',
  previewAllCoupons: 'Preview All Coupons',
  previewSampleCoupons: 'See a Coupon Sample',
  previewViewAllCoupons: 'Click to View All Coupons',
  authModalHeading: 'Almost there — save your coupons',
  authModalSubtext:
    'Your information is safe with us. We use bank-level encryption and will never share your details.',
  authModalLoginHeading: 'Welcome back',
  authModalLoginSubtext: 'Log in to see your coupons.',
  authModalTabSignup: 'Sign Up',
  authModalTabLogin: 'Log In',
  authModalSignupSubmit: 'Email me a magic link',
  authModalLoginSubmit: 'Log In',
  recipientRedeemButton: 'Redeem This ♥',
  postRedemptionState: 'This has been redeemed with love',
  recipientConversionHeading: 'Loved this gift?',
  recipientConversionSubtext: "Create your own — it's free.",
  recipientConversionButton: 'Create My Coupons →',
  ageGateConfirm: "I'm 18+, Continue →",
  ageGateDismiss: 'Go Back',
  pinWrongError: (senderName: string) =>
    `That PIN doesn't match. Check your message from ${senderName}.`,
  giftReadyPinInstruction: 'Share the link via WhatsApp. Send the PIN separately — or whisper it in person.',
  giftReadyShareMessage: (recipientName: string, senderName: string, shareLink: string) =>
    `${recipientName}, ${senderName} made you something special on Kindness Currency\n\nOpen it here:\n${shareLink}\n\nI'll send your PIN separately, so keep an eye out!`,
  giftReadyStartOver: 'Spot another template? Start a new coupon set →',
  templatesSubheading: 'Customize the perfect coupons. Start free.',
  comingSoonHeading: 'Coming Soon',
  comingSoonSubheading: "More ways to give — here's what's next.",
  footerTagline: 'Because the best gifts are promises kept.',
  navCreate: 'Create Coupons',
  navAboutUs: 'About Us',
  navProfile: 'Profile',
  navFeedback: 'Give Us Feedback',
  navAdmin: 'Admin',
  navLogIn: 'Log In / Sign Up',
  navLogOut: 'Log Out',
  feedbackHeading: 'Give Us Feedback',
  feedbackSubtext: "Tell us what's working, what isn't, or what you wish Kindness Currency did.",
  feedbackSubmitButton: 'Send Feedback',
  feedbackThankYou: 'Thank you for helping us grow ♥',
  profileHeading: 'Your Coupons',
  profileLoggedOutHeading: 'Log in to see your coupons',
  profileLoggedOutSubtext: "Open the menu and log in to view every coupon set you've sent.",
  profileEmptyState: "You haven't sent any coupon sets yet.",
  earlyAccessNamePlaceholder: 'Your name',
  earlyAccessEmailPlaceholder: 'Email address',
  earlyAccessSubmitButton: 'Notify Me',
  earlyAccessMissingName: 'Please enter your name',
  earlyAccessInvalidEmail: 'Please enter a valid email address',
  earlyAccessSuccess: 'You’re on the list! We’ll email you when it’s ready.',
  earlyAccessDuplicate: 'You’re already on the list for this one ♥',
  customCouponBookHeading: 'Get Early Access',
  customCouponBookSubheading: 'Build a coupon book entirely your way — every title, every promise, your words. Launching soon.',
  customCouponBookButton: 'Custom Coupon Books',
  featureInterestHeading: 'Custom Coupon Books',
  featureInterestSubtext: 'A fully custom coupon book, written from scratch — your words, your occasion, your rules. Be first to know when it launches.',
  featureInterestSubmitButton: 'Notify Me',
  featureInterestInvalidEmail: 'Please enter a valid email address',
  featureInterestThankYou: "You're on the list ♥",
  saveToAccountBanner: 'Save this to your account',
  addToAccountBanner: 'Add this to your account',
  profileTabSent: 'Sent',
  profileTabReceived: 'Received',
  profileReceivedEmptyState: "You haven't received any coupon sets yet.",
  giftMessageContinue: 'Continue',
  giftOpenCoupons: 'Open Your Coupons',
  giftInstructionsHeading: 'How Kindness Currency Works',
  giftRereadMessage: 'Read the message again',
  giftReminderButton: 'Reminders',
  giftReminderHeading: 'Want a nudge to redeem these?',
  giftReminderSubtext: "We'll send a gentle reminder — no pressure, and you can turn it off anytime.",
  giftReminderBiweekly: 'Every 2 weeks',
  giftReminderMonthly: 'Once a month',
  giftReminderQuarterly: 'Every 90 days',
  giftReminderOff: "Don't remind me",
  editMessageWriteLabel: 'Write a message',
  editMessageEditLabel: 'Edit your message',
  editMessageSubtext: "Something to say before they open it — optional, but it makes this feel like you.",
  editMessageSave: 'Save Message',
  resetPinButtonLabel: 'View PIN',
  resetPinConfirmHeading: 'Generate a new PIN?',
  resetPinConfirmBody: (recipientName: string) =>
    `There's no way to see the original PIN again — only a fresh one. The old PIN stops working right away, so you'll need to re-share the new one with ${recipientName}.`,
  resetPinConfirmSubmit: 'Generate New PIN',
  resetPinRevealedHeading: 'Here’s the new PIN',
  resetPinRevealedBody: 'Share it with the recipient separately from the link, just like the first time.',
  resetPinDone: 'Done',
  resetPinError: 'Something went wrong. Please try again.',
  resumedDraftBannerText: 'Continuing your last coupon set.',
  resumedDraftStartFreshButton: 'Not this one? Start fresh →',
  currentSetBadge: 'In progress',
  templateSwitchWarningHeading: 'Switch templates?',
  templateSwitchWarningBody: (currentTemplateName: string) =>
    `Your customized coupons for ${currentTemplateName} won't be saved if you switch.`,
  templateSwitchWarningResumeButton: (currentTemplateName: string) => `Go back to my ${currentTemplateName} coupons →`,
  filterPillAll: 'All coupons',
  filterPillFocused: 'One gesture, made specific',
  filterPillRange: 'Gestures, made for them',
  singleUseChooseCta: 'Choose This ♥',
  singleUseSectionHeading: 'One Clear Gesture',
  singleUseSectionSubheading: "Some gifts don't need a whole set — just the one thing you already know you want to give.",
  bundleSectionHeading: 'Many Ways To Show Up',
  bundleSectionSubheading:
    'Each ships with eight thoughtful coupons, ready to personalise — a few different ways to show up, all part of one story.',
  bundleTierPillEveryday: 'Everyday Kindness',
  bundleTierPillOccasion: 'For The Occasion',
  bundleTierPillRomance: 'Just The Two Of You',
  promoBannerMessage: 'Send 3 or more gifts together; the cheapest one is free, on us. Not valid for one-time gestures.',
  promoBannerDismiss: 'Dismiss',
  promoPopupHeading: 'Buy 3, Get the Cheapest Free',
  promoPopupBody: 'Send 3 or more gifts together; the cheapest one is free, on us. Not valid for one-time gestures.',
  promoPopupCta: 'See Full Pricing →',
  promoPopupDismiss: 'Not Right Now',
  pricingPageHeading: 'Pricing, Kept Simple',
  pricingPageSubheading: 'One-time, per coupon set — no subscriptions, ever.',
  pricingAvailableNow: 'Available now',
  pricingComingSoon: 'Coming soon',
  pricingFlagshipHeading: 'Custom Coupon Book',
  pricingFlagshipBody: 'Every title, every promise, your words — fully custom, launching soon.',
  pricingBundleNote: 'Buy 3 in one order and the cheapest is automatically free.',
  pricingPairNote: 'Made By Him & Made By Her are $9.99 together as a couple’s bundle, instead of $6.99 each.',
  addToCartCta: 'Add to Cart',
  inCartLabel: 'In Cart ✓',
  purchasedLabel: 'Purchased ✓',
  cartLinkLabel: (count: number) => `Cart (${count})`,
  cartHeading: 'Your Cart',
  cartEmptyMessage: 'Nothing here yet.',
  cartBrowseLink: 'Browse templates',
  cartAlmostThreeForTwo: (remaining: number) =>
    `Add ${remaining} more coupon ${remaining === 1 ? 'set' : 'sets'} and the cheapest one is free.`,
  cartRemoveLabel: (name: string) => `Remove ${name} from cart`,
  cartCheckoutCta: 'Checkout →',
  cartCheckoutHeading: 'Checkout',
  cartCheckoutNote: "Billing isn't live yet — this marks the order as placed without charging a card.",
  cartPayCta: (total: string) => `Pay $${total}`,
  cartDoneHeading: "You're all set ♥",
  cartDoneBody: "Billing isn't live yet, so nothing was charged — consider these yours for now. Personalize each one whenever you're ready.",
  cartPersonalizeCta: 'Personalize My Coupons →',
  gesturePreviewCta: 'Preview This Coupon',
  gestureCustomizedLabel: 'Customized ✓',
  gestureDefaultLabel: 'Using the original wording',
  gestureSendPendingHeading: 'Coming Soon',
  gestureSendPendingBody: "Sending and saving one-time gestures isn't live yet — you just walked through exactly what it'll feel like once it is.",
} as const
