export const ctaCopy = {
  heroCta: 'Create My Coupons',
  sendWithLove: 'Send with Love',
  saveMyCoupons: 'Save My Coupons',
  previewAllCoupons: 'Preview All Coupons',
  previewSampleCoupons: 'See a Coupon Sample',
  authModalHeading: 'Almost there — save your coupons',
  authModalSubtext:
    'Your information is safe with us. We use bank-level encryption and will never share your details.',
  recipientRedeemButton: 'Redeem This ♥',
  postRedemptionState: 'This has been redeemed with love',
  recipientConversionHeading: 'Loved this gift?',
  recipientConversionSubtext: "Create your own — it's free.",
  recipientConversionButton: 'Create My Coupons →',
  ageGateConfirm: "I'm 18+, Continue →",
  ageGateDismiss: 'Go Back',
  pinWrongError: (senderName: string) =>
    `That PIN doesn't match. Check your message from ${senderName}.`,
  giftReadyPinInstruction: 'Share the link via WhatsApp. Send the PIN separately — or whisper it in person.',
  giftReadyStartOver: 'Spot a typo? Start a new coupon set →',
  templatesSubheading: 'Customize the perfect coupons. Start free.',
  footerTagline: 'Because the best gifts are promises kept.',
  navAboutUs: 'About Us',
  navProfile: 'Profile',
  navFeedback: 'Give Us Feedback',
  navLogIn: 'Log In',
  navLogOut: 'Log Out',
  feedbackHeading: 'Give Us Feedback',
  feedbackSubtext: "Tell us what's working, what isn't, or what you wish Kindness Currency did.",
  feedbackSubmitButton: 'Send Feedback',
  feedbackThankYou: 'Thank you for helping us grow ♥',
  profileHeading: 'Your Coupons',
  profileLoggedOutHeading: 'Log in to see your coupons',
  profileLoggedOutSubtext: "Open the menu and log in to view every coupon set you've sent.",
  profileEmptyState: "You haven't sent any coupon sets yet.",
} as const
