export const ctaCopy = {
  heroCta: 'Create My Coupons',
  sendWithLove: 'Send with Love',
  saveMyCoupons: 'Save My Coupons',
  sendPaymentRedirecting: 'Redirecting you to checkout…',
  previewAllCoupons: 'Preview All Coupons',
  previewSampleCoupons: 'How You Create Your Perfect Gift',
  howYouCreateStepPersonalize: 'Personalize',
  howYouCreateStepPreview: 'Preview',
  howYouCreateStepSend: 'Send',
  howYouCreatePersonalizeBody: 'Edit every title, tweak the message, and pick the colors — make all 8 coupons your own.',
  howYouCreateDetailsStepLabel: "Step 2 · Who's it for?",
  howYouCreateEditStepLabel: 'Step 3 · Personalize each coupon',
  howYouCreateNext: 'Next →',
  howYouCreateBack: '← Back',
  howYouCreateDone: 'Done',
  howYouCreateSenderName: 'Your Name',
  howYouCreateRecipientBanner: 'This is what your loved one sees',
  authModalHeading: 'Almost there — save your coupons',
  authModalSubtext: "Just enough to keep your coupons safe and the surprise intact — we'll never share your email.",
  authModalLoginHeading: 'Welcome back',
  authModalLoginSubtext: 'Log in to see your coupons.',
  authModalTabSignup: 'Sign Up',
  authModalTabLogin: 'Log In',
  authModalSignupSubmit: 'Email me a magic link',
  authModalLoginSubmit: 'Log In',
  recipientRedeemButton: 'Redeem This ♥',
  postRedemptionState: 'This has been redeemed with love',
  recipientConversionHeading: 'Loved this gift?',
  recipientConversionSubtext: "Create your own — it's free.",
  recipientConversionButton: 'Create My Coupons →',
  ageGateConfirm: "I'm 18+, Continue →",
  ageGateDismiss: 'Go Back',
  pinWrongError: (senderName: string) =>
    `That PIN doesn't match. Check your message from ${senderName}.`,
  pinLockedError: 'Too many wrong PINs — this coupon is locked for 15 minutes. Please try again later.',
  giftReadyPinInstruction: 'Share the link via WhatsApp. Send the PIN separately — or whisper it in person.',
  giftReadyShareMessage: (recipientName: string, senderName: string, shareLink: string) =>
    `${recipientName}, ${senderName} made you something special on Kindness Currency\n\nOpen it here:\n${shareLink}\n\nI'll send your PIN separately, so keep an eye out!`,
  giftReadyStartOver: 'Spot another template? Start a new coupon set →',
  templatesSubheading: 'Customize the perfect coupons. Start free.',
  comingSoonHeading: 'Coming Soon',
  comingSoonSubheading: "More ways to give — here's what's next.",
  footerTagline: 'Because the best gifts are promises kept.',
  navCreate: 'Create Coupons',
  navAboutUs: 'About Us',
  navProfile: 'Your Gifts',
  navFeedback: 'Give Us Feedback',
  navAdmin: 'Admin',
  navLogIn: 'Log In / Sign Up',
  navLogOut: 'Log Out',
  feedbackHeading: 'Give Us Feedback',
  feedbackSubtext: "Tell us what's working, what isn't, or what you wish Kindness Currency did.",
  feedbackSubmitButton: 'Send Feedback',
  feedbackThankYou: 'Thank you for helping us grow ♥',
  profileHeading: 'Your Gifts',
  profileLoggedOutHeading: 'Log in to see your coupons',
  profileLoggedOutSubtext: "Open the menu and log in to view every coupon set you've sent.",
  profileEmptyState: "You haven't sent any coupon sets yet.",
  earlyAccessNamePlaceholder: 'Your name',
  earlyAccessEmailPlaceholder: 'Email address',
  earlyAccessSubmitButton: 'Notify Me',
  earlyAccessMissingName: 'Please enter your name',
  earlyAccessInvalidEmail: 'Please enter a valid email address',
  earlyAccessSuccess: 'You’re on the list! We’ll email you when it’s ready.',
  earlyAccessDuplicate: 'You’re already on the list for this one ♥',
  customCouponBookHeading: 'Get Early Access',
  customCouponBookSubheading: 'Build a coupon book entirely your way — every title, every promise, your words. Launching soon.',
  customCouponBookButton: 'Custom Coupon Books',
  featureInterestHeading: 'Custom Coupon Books',
  featureInterestSubtext: 'A fully custom coupon book, written from scratch — your words, your occasion, your rules. Be first to know when it launches.',
  featureInterestSubmitButton: 'Notify Me',
  featureInterestInvalidEmail: 'Please enter a valid email address',
  featureInterestThankYou: "You're on the list ♥",
  saveToAccountBanner: 'Save this to your account',
  addToAccountBanner: 'Add this to your account',
  profileTabSent: 'Sent',
  profileTabReceived: 'Received',
  profileReceivedEmptyState: "You haven't received any coupon sets yet.",
  giftMessageContinue: 'Continue',
  giftOpenCoupons: 'Open Your Coupons',
  giftInstructionsHeading: 'How Kindness Currency Works',
  giftRereadMessage: 'Read the message again',
  giftReminderButton: 'Reminders',
  giftReminderHeading: 'Want a nudge to redeem these?',
  giftReminderSubtext: "We'll send a gentle reminder — no pressure, and you can turn it off anytime.",
  giftReminderBiweekly: 'Every 2 weeks',
  giftReminderMonthly: 'Once a month',
  giftReminderQuarterly: 'Every 90 days',
  giftReminderOff: "Don't remind me",
  editMessageWriteLabel: 'Write a message',
  editMessageEditLabel: 'Edit your message',
  editMessageSubtext: "Something to say before they open it — optional, but it makes this feel like you.",
  editMessageSave: 'Save Message',
  messageStarterPrompt: '✨ Need a starting point?',
  messageStarterHint: 'Tap to use this',
  resetPinButtonLabel: 'View PIN',
  resetPinConfirmHeading: 'Generate a new PIN?',
  resetPinConfirmBody: (recipientName: string) =>
    `There's no way to see the original PIN again — only a fresh one. The old PIN stops working right away, so you'll need to re-share the new one with ${recipientName}.`,
  resetPinConfirmSubmit: 'Generate New PIN',
  resetPinRevealedHeading: 'Here’s the new PIN',
  resetPinRevealedBody: 'Share it with the recipient separately from the link, just like the first time.',
  resetPinDone: 'Done',
  resetPinError: 'Something went wrong. Please try again.',
  resumedDraftBannerText: 'Continuing your last coupon set.',
  resumedDraftStartFreshButton: 'Not this one? Start fresh →',
  authLinkFailedBannerText: "That sign-in link didn't work — it may have expired, already been used, or been opened on a different device.",
  authLinkFailedRetryButton: 'Try signing in again',
  currentSetBadge: 'In progress',
  templateSwitchWarningHeading: 'Switch templates?',
  templateSwitchWarningBody: (currentTemplateName: string) =>
    `Your customized coupons for ${currentTemplateName} won't be saved if you switch.`,
  templateSwitchWarningResumeButton: (currentTemplateName: string) => `Go back to my ${currentTemplateName} coupons →`,
  filterPillAll: 'All coupons',
  filterPillFocused: 'One gesture, made specific',
  filterPillRange: 'Gestures, made for them',
  singleUseFreeCta: 'Design Your Gift · Free',
  singleUseSectionHeading: 'One Clear Gesture',
  singleUseSectionSubheading: "Some gifts don't need a whole set — just the one thing you already know you want to give.",
  bundleSectionHeading: 'Many Ways To Show Up',
  bundleSectionSubheading:
    'Each ships with eight thoughtful coupons, ready to personalise — a few different ways to show up, all part of one story.',
  bundleTierPillEveryday: 'Everyday Kindness',
  bundleTierPillOccasion: 'For The Occasion',
  bundleTierPillRomance: 'Just The Two Of You',
  promoBannerMessage: 'Send 3 or more gifts together; the cheapest one is free, on us. Not valid for one-time gestures.',
  promoBannerDismiss: 'Dismiss',
  promoPopupHeading: 'Buy 3, Get the Cheapest Free',
  promoPopupBody: 'Send 3 or more gifts together; the cheapest one is free, on us. Not valid for one-time gestures.',
  promoPopupCta: 'See Full Pricing →',
  promoPopupDismiss: 'Not Right Now',
  pricingPageHeading: 'Pricing, Kept Simple',
  pricingPageSubheading: 'One-time, per coupon set — no subscriptions, ever.',
  pricingAvailableNow: 'Available now',
  pricingComingSoon: 'Coming soon',
  pricingFlagshipHeading: 'Custom Coupon Book',
  pricingFlagshipBody: 'Every title, every promise, your words — fully custom, launching soon.',
  pricingBundleNotePrefix: 'Buy ',
  pricingBundleNoteHighlight: '3 or more',
  pricingBundleNoteSuffix: ' in one order and get the cheapest free.',
  pricingPairNote: (formattedPairPrice: string, formattedEachPrice: string) =>
    `Requested By Him & Requested By Her are ${formattedPairPrice} together as a couple’s bundle, instead of ${formattedEachPrice} each.`,
  designMyGiftCta: (formattedPrice: string) => `Design My Gift · ${formattedPrice}`,
  designMyGiftAddedCta: 'Added ✓',
  qtyDecreaseLabel: (name: string) => `Decrease quantity for ${name}`,
  qtyIncreaseLabel: (name: string) => `Increase quantity for ${name}`,
  pendingToPersonalizeBadge: (count: number) => (count === 1 ? '1 to personalize' : `${count} to personalize`),
  cartLinkLabel: (count: number) => `Cart (${count})`,
  cartHeading: 'Your Cart',
  cartEmptyMessage: 'Nothing here yet.',
  cartBrowseLink: 'Browse templates',
  cartAlmostThreeForTwo: (remaining: number) =>
    `Add ${remaining} more coupon ${remaining === 1 ? 'book' : 'books'} and the cheapest one is free.`,
  cartPairDiscountLabel: "Couple's bundle discount",
  cartRemoveLabel: (name: string) => `Remove ${name} from cart`,
  cartCheckoutCta: 'Checkout →',
  cartCheckoutHeading: 'Checkout',
  cartCheckoutNote: "You'll pay securely via Paystack, then come back here to personalize each one.",
  cartPayCta: (formattedTotal: string) => `Pay ${formattedTotal}`,
  cartDoneHeading: "You're all set ♥",
  cartDoneBody: "Payment's confirmed — these are yours now. Personalize each one whenever you're ready.",
  cartSeeMyGiftsCta: 'See My Gifts →',
  cartPaymentFailedHeading: "That didn't go through",
  cartPaymentFailedBody: "Your payment wasn't completed, so nothing was charged and nothing was added to your account. Your cart is still waiting for you.",
  cartPaymentFailedCta: 'Back to Cart',
  gesturePreviewCta: 'Preview This Coupon',
  gestureCustomizedLabel: 'Customized ✓',
  gestureDefaultLabel: 'Using the original wording',
  gestureUnlockCta: (formattedPrice: string) => `Make This Gift Yours · ${formattedPrice}`,
  gestureUnlockConfirmHeading: 'Make this gift truly yours?',
  gestureUnlockConfirmBody: "Add your own words, not just the look — you'll pay securely via Paystack before it sends.",
  gestureUnlockConfirmCta: (formattedPrice: string) => `Make It Mine · ${formattedPrice}`,
  gestureUnlockDismiss: 'Keep the original wording',
  giftTrackingBackAria: 'Back to Your Gifts',
  giftTrackingStatusSent: (recipientName: string) => `Your gift is on its way to ${recipientName}.`,
  giftTrackingStatusSeen: (recipientName: string) => `${recipientName} has seen your gift.`,
  giftTrackingStatusRedeemed: (recipientName: string) => `${recipientName} is putting your gift to good use.`,
  giftTrackingProgress: (redeemed: number, total: number) => `${redeemed} of ${total} coupon${total === 1 ? '' : 's'} redeemed so far.`,
  giftTrackingItemsHeading: 'Your Coupons',
  giftTrackingCouponRedeemed: 'Redeemed',
  giftTrackingCouponPending: 'Not yet redeemed',
  giftTrackingHistoryHeading: 'Gift Journey',
  giftTrackingHistorySent: 'Gift sent',
  giftTrackingHistorySeen: 'Seen by recipient',
  giftTrackingHistoryRedeemed: 'First coupon redeemed',
  giftTrackingHistoryPendingSeen: 'Not yet opened',
  giftTrackingHistoryPendingRedeemed: 'Not yet redeemed',
  giftTrackingRecipientLabel: 'Sent to',
  giftTrackingCopyLink: 'Copy Link',
  giftTrackingCopyLinkDone: 'Link Copied ✓',
  giftTrackingResendShare: 'Resend Link',
  ourStoryLinkLabel: 'Read Our Story →',
} as const
